command=/bin/sh -c "$command"
separator_block_width=18
markup=none

[debug]
label=DBG
command=~/.config/sway/blocks/lumo_debug_block.sh
interval=1
color=#ffcc66
min_width=DBG waiting for log...
align=left

[clock]
label=TIME
command=~/.config/sway/blocks/clock_block.sh
interval=1
color=#ffffff
min_width=TIME 00:00:00
align=right

[battery]
command=battery.sh
interval=10

[counter]
_count=0
command=printf '{"full_text":"Counter: %s", "_count":%d}\n' $_count $((_count + 1))
format=json
interval=1
